### ISSUE TITLE
[Critical] Versions synced on Central are not enough to build the same pom without mvnpm repo

### ISSUE THREAD

**Issue by ia3andy** [mvnpm/mvnpm#1020]
Because of this, a build which passes with mvnpm repo enabled (and the synced with central done) doesn't work on CI (without mvnpm repo).

**Comment by ia3andy** [comment]
Still I wonder why when removing the mvnpm profile I got this log:
```
ERROR] Failed to execute goal on project quarkus-react: Could not resolve dependencies for project org.acme:quarkus-react:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.mvnpm:react:jar:18.2.0 -> org.mvnpm:loose-envify:jar:1.1.0 -> org.mvnpm:js-tokens:jar:[1.0.1,2): No versions available for org.mvnpm:js-tokens:jar:[1.0.1,2) within specified range -> [Help 1]
```

While with the mvnpm profile on `loose-envify` was 1.4.0.

This exact case is not reproducible as it is now synced.

**Comment by ia3andy** [comment]
ok I think I've got it, it's not problem of versions path, but that Maven wants all the different combination to be "available", having one working path is not enough, even if this is the right working path.

**Comment by ia3andy** [comment]
so our job to fix this is to, when syncing a given jar, to also sync all the latest version of all the ranges in its dependencies (and so on).

**Comment by phillip-kruger** [comment]
At the momentwe sync the matched on in a range as requested, and it a later one exists, that will also be synced later. That is enough for central, but I assume the sync of the matched range failed. I will check and revert

**Comment by ia3andy** [comment]
Closing in favor of https://github.com/mvnpm/mvnpm/issues/4614
