### ISSUE TITLE
Some NPM Zip Files are not able to be opened by ZipFileSystem

### ISSUE THREAD

**Issue by chrisruffalo** [mvnpm/mvnpm#3071]
As an example:
> [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.6.4:dev (default-cli) on project api-doc-test: Quarkus code generation phase has failed: Failed to inject extension deployment dependencies: Failed to read /home/chris/.m2/repository/org/mvnpm/at/swagger-api/apidom-core/0.91.0/apidom-core-0.91.0.jar: Failed to create a new filesystem for /home/chris/.m2/repository/org/mvnpm/at/swagger-api/apidom-core/0.91.0/apidom-core-0.91.0.jar: ZIP file can't be opened as a file system because entry "/META-INF/resources/_static/apidom-core/0.91.0/./cjs/index.cjs" has a '.' or '..' element in its name -> [Help 1]

I am not sure _who_ has responsibility for this error or how to work around it. All of the apidom-* dependencies seem to be packaged this way.

Reproducer: https://github.com/chrisruffalo/api-doc-test

**Comment by chrisruffalo** [comment]
It looks like this has been fixed in the 0.92.0 version of @swagger-ui/apidom-core. I am still going to see if I can fix this on the mvnpm tar -> zip side which looks fairly straightforward. This, however, wouldn't even fix any that had already been completed.

**Comment by chrisruffalo** [comment]
See: https://github.com/mvnpm/mvnpm/pull/3503

**Comment by phillip-kruger** [comment]
@chrisruffalo thanks for all the issues, I'll have a look soon ( on PTO at the moment). Let me know if it's urgent then I can try and look earlier

**Comment by chrisruffalo** [comment]
@phillip-kruger absolutely not critical. enjoy pto.
