### ISSUE TITLE
Add a "in progress" status when a Central sync is not yet available on Central but already released

### ISSUE THREAD

**Issue by ia3andy** [mvnpm/mvnpm#46]
<img width="728" alt="image" src="https://github.com/mvnpm/mvnpm/assets/2223984/900f250f-0a94-4877-a90e-5793ee3dd92c">

<img width="1388" alt="image" src="https://github.com/mvnpm/mvnpm/assets/2223984/4815f5fe-97cc-48d8-992b-025678c7db19">

**Comment by ia3andy** [comment]
And add a note in the announcement that "It will be available as soon as Maven Central is updated with the new release"

**Comment by phillip-kruger** [comment]
This will indicate in the new info page
