### ISSUE TITLE
[Critical] peerDependencies should be added as normal Maven dependencies

### ISSUE THREAD

**Issue by ia3andy** [mvnpm/mvnpm#5727]
From https://nodejs.org/en/blog/npm/peer-dependencies
It seems that peer dependencies should be translated into normal Maven dependencies.
For example, when you import bootstrap, you should also have core@popperjs

**Comment by phillip-kruger** [comment]
Are you doing a PR for the fix ?

**Comment by ia3andy** [comment]
@phillip-kruger if you can't do it before, I'll have look next week.

**Comment by phillip-kruger** [comment]
I started look at this. I need to fix something else, so will do this too

**Comment by phillip-kruger** [comment]
Fixed
