### ISSUE TITLE
@mui/utils fails and hangs in webui and maven-metadata.xml is empty

### ISSUE THREAD

**Issue by davidvoit** [mvnpm/mvnpm#7179]
https://repo.mvnpm.org/maven2/org/mvnpm/at/mui/utils/maven-metadata.xml returns an empty file.

![image](https://github.com/mvnpm/mvnpm/assets/12702/6e01679a-999f-49bc-8ef2-832f4a356c2b)
Hangs and shows nothing

**Comment by phillip-kruger** [comment]
I'll have a look

**Comment by davidvoit** [comment]
Thanks for the fast fix!
Looking forward to the next release to continue testing :-)

**Comment by phillip-kruger** [comment]
You can try it out already

**Comment by davidvoit** [comment]
Sadly the maven-metadata.xml is still empty here:
$ curl -v https://repo.mvnpm.org/maven2/org/mvnpm/at/mui/utils/maven-metadata.xml
* Host repo.mvnpm.org:443 was resolved.
* IPv6: (none)
* IPv4: 148.72.247.54
*   Trying 148.72.247.54:443...
* Connected to repo.mvnpm.org (148.72.247.54) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / RSASSA-PSS
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=repo.mvnpm.org
*  start date: Apr 11 19:44:24 2024 GMT
*  expire date: Jul 10 19:44:23 2024 GMT
*  subjectAltName: host "repo.mvnpm.org" matched cert's "repo.mvnpm.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET /maven2/org/mvnpm/at/mui/utils/maven-metadata.xml HTTP/1.1
> Host: repo.mvnpm.org
> User-Agent: curl/8.6.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 200 OK
< Server: nginx/1.18.0 (Ubuntu)
< Date: Wed, 05 Jun 2024 06:22:41 GMT
< Content-Type: application/xml;charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host repo.mvnpm.org left intact

**Comment by davidvoit** [comment]
https://mvnpm.org/search/@mui/utils

This also hangs the web ui

**Comment by phillip-kruger** [comment]
40828

**Comment by davidvoit** [comment]
Now it was working fine, thanks! Got mui working, even if I had to manual pin two dependencies

**Comment by phillip-kruger** [comment]
Great !
