### ISSUE TITLE
The patternfly dependency makes mvnpm clone npm - kinda 

### ISSUE THREAD

**Issue by fbricon** [mvnpm/mvnpm#881]
Using the quarkus web bundler, I just added `org.mvnpm:patternfly:3.59.5` to my dependencies. Now the build has been downloading all versions of everything, for the past 35 min (and counting):

```
Downloading from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.5/d3-time-1.0.5.pom
Downloaded from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.5/d3-time-1.0.5.pom (1.3 kB at 1.3 kB/s)
Downloading from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.6/d3-time-1.0.6.pom
Downloaded from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.6/d3-time-1.0.6.pom (1.1 kB at 1.0 kB/s)
Downloading from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.7/d3-time-1.0.7.pom
Downloaded from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.7/d3-time-1.0.7.pom (1.1 kB at 925 B/s)
Downloading from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.8/d3-time-1.0.8.pom
Downloaded from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.8/d3-time-1.0.8.pom (1.1 kB at 664 B/s)
Downloading from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.9/d3-time-1.0.9.pom
Downloaded from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.9/d3-time-1.0.9.pom (1.1 kB at 971 B/s)
Downloading from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.10/d3-time-1.0.10.pom
Downloaded from mvnpm.org: https://repo.mvnpm.org/maven2/org/mvnpm/at/types/d3-time/1.0.10/d3-time-1.0.10.pom (1.1 kB at 727 B/s)
```

patternfly relies on version ranges, which is kinda bad, but npm itself can resolve it in seconds, so there's likely room for improvements in the way mvnpm handles ranges

**Comment by fbricon** [comment]
Looks like my build may have broken mvnpm

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  01:11 h
> [INFO] Finished at: 2023-10-10T10:15:37+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project quatternfly: Could not resolve dependencies for project org.acme:quatternfly:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.mvnpm:patternfly:jar:3.59.5 -> org.mvnpm:bootstrap-datepicker:jar:1.7.1 -> org.mvnpm:jquery:jar:1.7.2 -> org.mvnpm:jsdom:jar:0.2.14 -> org.mvnpm:request:jar:2.54.0 -> org.mvnpm:har-validator:jar:1.4.0 -> org.mvnpm:commander:jar:2.7.1: Failed to read artifact descriptor for org.mvnpm:commander:jar:2.7.1: The following artifacts could not be resolved: org.mvnpm:commander:pom:2.7.1 (absent): Could not transfer artifact org.mvnpm:commander:pom:2.7.1 from/to mvnpm.org (https://repo.mvnpm.org/maven2): status code: 500, reason phrase: Internal Server Error (500) -> [Help 1]

**Comment by ia3andy** [comment]
@fbricon thanks for reporting @phillip-kruger will have a look :)

**Comment by phillip-kruger** [comment]
Thanks for the bug report @fbricon.

I would assume the npm build has a lock file that will make it much faster, as the specific versions are locked. At this point we don't have a way to automatically create a lock file, but it's something we are working on. Creating the lock should be quicker than resolving the ranges with maven. For now, if you want, we can manually lock them by adding the latest version in the range in you dependency. (Basically what we will do, but automatically)

Apart from supporting lock file, we have discussed narrowing the ranges in some cases, we already do it for `*`, but not for anything else. I don't think we can change the way maven resolve a range, so the only thing we can do it to narrow the range when we translate from package.json in npm resistry. But that can also be dangerous , which is wht we have not done anything there, and rather try and stay as close as we can to the package.json

W.r.t your second issue, I can see the error in the log, and will fix that, I'll let you know once that is done. There seems to be a version number translation that is not working.

Thanks again

**Comment by fbricon** [comment]
even without a lock file, package.json resolution for the single patternfly dependency takes a few seconds

**Comment by phillip-kruger** [comment]
I believe you :) I just don't think we can change the way maven resolve ranges. NPM is obviously better with it that maven.  Maven first want to download all metadata. If you know a way to change that in maven, please help :)

**Comment by phillip-kruger** [comment]
@fbricon - your second issue (the 500 error) is now fixed. Please let me know. Thanks

**Comment by fbricon** [comment]
still seeing 500s

> [ERROR] Failed to execute goal on project quatternfly: Could not resolve dependencies for project org.acme:quatternfly:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.mvnpm:patternfly:jar:3.59.5 -> org.mvnpm:bootstrap-datepicker:jar:1.7.1 -> org.mvnpm:jquery:jar:1.7.2 -> org.mvnpm:jsdom:jar:0.2.14 -> org.mvnpm:request:jar:2.65.0 -> org.mvnpm:har-validator:jar:2.0.2 -> org.mvnpm:pinkie-promise:jar:1.0.0 -> org.mvnpm:pinkie:jar:1.0.0: Failed to read artifact descriptor for org.mvnpm:pinkie:jar:1.0.0: The following artifacts could not be resolved: org.mvnpm:pinkie:pom:1.0.0 (absent): Could not transfer artifact org.mvnpm:pinkie:pom:1.0.0 from/to mvnpm.org (https://repo.mvnpm.org/maven2): status code: 500, reason phrase: Internal Server Error (500) ->

**Comment by ia3andy** [comment]
@phillip-kruger to lock a version it should be in dependency management right (or dependencies is ok)?

**Comment by phillip-kruger** [comment]
I think either

**Comment by phillip-kruger** [comment]
@fbricon I created a re-creator, and found a lot of issues (patternfly is a big project with many dependencies, ideal test case). Some of the issues were 

- spaces after operator in the version (> 1 vs >1) - fixed
- versions that point to a github repo (this is legal in NPM to support private repos) - bypassed in this this case , not supported in mvnpm. In this case it's used in a old version that is being pulled in due to ranges.
- Upper boundry without an operator in a version range - fixed

For now, you should be able to build a project by adding the following to your pom:

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.mvnpm</groupId>
                <artifactId>patternfly</artifactId>
                <version>3.59.5</version>
            </dependency>
            <dependency>
                <groupId>org.mvnpm</groupId>
                <artifactId>jquery</artifactId>
                <version>3.7.1</version>
            </dependency>
            <dependency>
                <groupId>org.mvnpm</groupId>
                <artifactId>d3</artifactId>
                <version>3.5.17</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.mvnpm</groupId>
            <artifactId>patternfly</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
```

Now, this is not ideal, as we would rather just be able to add patternfly and let the dependencies being pulled in, but the github url version is breaking this. I'll open an issue to look if we can support somehow

**Comment by phillip-kruger** [comment]
@fbricon Any more feedback ? Is it better now ? You can also use the locker that is now available.
