### ISSUE TITLE
no version available for transitive dependencies

### ISSUE THREAD

**Issue by nimo23** [mvnpm/mvnpm#9896]
**Describe the bug**
I use Quarkus with quarkus-web-bundler and when I trying to import:

		<dependency>
			<groupId>org.mvnpm</groupId>
			<artifactId>primereact</artifactId>
			<version>10.8.4</version>
			<scope>provided</scope>
		</dependency>

then I get this error:

```
Could not collect dependencies for project com.acme:hello:jar:1.0.0-SNAPSHOT
[ERROR] No versions available for org.mvnpm:scheduler:jar:[16.6.2,17) within specified range
[ERROR] No versions available for org.mvnpm:scheduler:jar:[16.6.2,17) within specified range
```

**To Reproduce**
1. Add the following to pom.xml:

```
<!-- Add quarkus 3.16.1 -->
..
<dependency>
    <groupId>io.quarkiverse.web-bundler</groupId>
    <artifactId>quarkus-web-bundler</artifactId>
    <version>1.7.3</version>
</dependency>
<dependency>
    <groupId>org.mvnpm</groupId>
    <artifactId>primereact</artifactId>
    <version>10.8.4</version>
    <scope>provided</scope>
</dependency>
```

3. Update maven deps

**Expected behavior**
The lib should be downloaded without error.

**Additional context**
I used mvnpm for the first time. I don't know if this is really a bug or if I have to take care of downloading the lib `scheduler` myself but I expect the specified libraries in mvnpm (in this case: primereact) to take care of transitive deps themselves.

**Comment by phillip-kruger** [comment]
Are you using the repository in your settings ?

```
<settings>
    <profiles>
        <profile>
            <id>mvnpm-repo</id>
            <repositories>
                <repository>
                    <id>central</id>
                    <name>central</name>
                    <url>https://repo.maven.apache.org/maven2</url>
                </repository>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>mvnpm.org</id> 
                    <name>mvnpm</name>
                    <url>https://repo.mvnpm.org/maven2</url>
                </repository>
            </repositories>
        </profile>
    </profiles>
</settings>
```

typically /home/your-username/.m2/settings.xml

You only need to add this on your development laptop, in CI it should then already be synced to maven

**Comment by phillip-kruger** [comment]
Yea that is strange. We need to figure out what dependency is pulling that in transitively. Can you see that in your IDE ?

**Comment by phillip-kruger** [comment]
Ok let me see if I can find it. Hold on

**Comment by phillip-kruger** [comment]
Can you share your pom.xml (or at least a list of all mvnpm deps )

**Comment by phillip-kruger** [comment]
Ok, give me a few mins let me find it

**Comment by phillip-kruger** [comment]
Try to add an exclusion on react-router-dom :

```
<dependency>
		<groupId>org.mvnpm</groupId>
		<artifactId>react-router-dom</artifactId>
		<version>6.27.0</version>
		<scope>runtime</scope>
                <exclusions>
                    <exclusion>
                        <groupId>org.mvnpm</groupId>
                        <artifactId>scheduler</artifactId>
                    </exclusion>
                </exclusions>
	</dependency>
	```
	
	You can also then remove the 
	
	```
	<groupId>org.mvnpm</groupId>
	<artifactId>scheduler</artifactId>
	```
	
	I am still trying to figure out why that version is there. Let me know if this works for you

**Comment by phillip-kruger** [comment]
I still can not see where that version is pulled in. I'll dig some more

**Comment by phillip-kruger** [comment]
I get this error on my laptop with your reproducer, I am reopening and investigating

**Comment by phillip-kruger** [comment]
I fixed some of the issues highlighted by this reproducer. It's' working now for me if you exclude the scheduler:

```
<dependency>
                        <groupId>org.mvnpm</groupId>
                        <artifactId>react-router-dom</artifactId>
                        <version>5.3.4</version>
                        <scope>provided</scope>
                        <exclusions>
                          <exclusion>
                              <groupId>org.mvnpm</groupId>
                              <artifactId>scheduler</artifactId>
                          </exclusion>
                      </exclusions>
                </dependency>
```

I'll release a new version a.s.a.p

**Comment by phillip-kruger** [comment]
The problem is that somewhere, a dependency reference a scheduler version that does not exist. I could not find where, excepts that it's somewhere in `react-router-dom`
